CREATE SEQUENCE USUARIO_ID_SEQ;

CREATE TABLE USUARIO (
USUA_ID_USUARIO integer NOT NULL DEFAULT nextval('USUARIO_ID_SEQ'),
CLIE_CD_CLIENTE integer,
USUA_NM_USUARIO varchar(200) not null,
USUA_DS_PASSWORD varchar(500) not null,
USUA_NM_ROLE varchar(1000) ,
CONSTRAINT PK_USUARIO PRIMARY KEY (USUA_ID_USUARIO),
CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIE_CD_CLIENTE) REFERENCES CLIENTE(CLIE_CD_CLIENTE)
);